### ISSUE TITLE
check for backup folder on launch

### ISSUE THREAD

**Issue by zweilous** [Ryuzaki-MrL/CacheTool#17]
if `/3ds/data/cthulhu` doesn't exist, trying to back up the home menu or shared icon cache will cause a crash. can something be added to check if the folder exists and create it if needed?

**Comment by Ryuzaki-MrL** [comment]
Prior to 1.3.3, Cthulhu used to store userdata in `/3ds/data/cthulhu`, and it created the folder.
I changed the directory creation to `/3ds/Cthulhu` but forgot to actually change the path on the rest of the code.

Thanks for poiting it out!
