### ISSUE TITLE
Not a real issue

### ISSUE THREAD

**Issue by BernardoGiordano** [Ryuzaki-MrL/CacheTool#2]
I managed to modify your code and add successfully a simple way to go to the first menu entry to the last, and viceversa. They're about 10 lines of code but I'm assuming that your notepad works differently from mine, and it appears that I write more code that I've made. 

Here are the modifications:
- https://github.com/BernardoGiordano/CacheTool/blob/master/source/main.cpp#L605 (you only have to modify this value if you add new entries, the algorithm will still work)
- https://github.com/BernardoGiordano/CacheTool/blob/master/source/main.cpp#L649-L663 (actual modification)

I uploaded the code on a fork. Feel free to copy/paste these lines or to made me able to make a pull request. I'll erase my fork after your aggreement or disagreement with this enhancements :)

**Comment by Ryuzaki-MrL** [comment]
I'm already reworking the UI and also spliting the entries into submenus, but thanks anyway.
