### ISSUE TITLE
Not working on N3DS XL

### ISSUE THREAD

**Issue by Masamune3210** [Ryuzaki-MrL/CacheTool#6]
Open app, waits for a minute, then dies with a Data Abort

Can send dumps if needed, glad to help debugging if needed

**Comment by AnalogMan151** [comment]
Same issue here. Crashes on n3DS USA model.

**Comment by Ryuzaki-MrL** [comment]
I think I've found the issue
Can you both try these 2 builds?

http://gbatemp.net/attachments/cthulhu_1-zip.80075/
http://gbatemp.net/attachments/cthulhu_2-zip.80076/

Thanks.

**Comment by Masamune3210** [comment]
Sorry, didnt notice the response, trying now. Just taking a nand backup real quick just in case something goes wrong

**Comment by deadair3210** [comment]
Any particular preference of which one to try first?

**Comment by deadair3210** [comment]
Both launch, the Cthulhu_2 crashed on n3ds when messing with the software library, but worked fine on the XL

**Comment by deadair3210** [comment]
This is what happens on the normal new 3ds
![17195307_1274846285935306_1814485522_o](https://cloud.githubusercontent.com/assets/1053504/23684766/58b1d38e-0366-11e7-8045-7c73ff7abf42.jpg)

**Comment by Masamune3210** [comment]
Never mind, everything is working a-ok with the second one, except for a small prefetch abort that randomly seems to pop up every once in a while
